/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.js' */
"use strict";

module.exports = {
    configs: {
        recommended: require("./configs/recommended")
    },
    rules: {
        "example-rule": require("./rules/example-rule")
    }
};
