/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
    plugins: ["xxxx"],
    rules: {
        "xxxx/example-rule": "error"
    }
};
